//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KB_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string Tag { get; set; }
        public string Note { get; set; }
        public byte[] Attachment { get; set; }

        //One-too-many relationship
        public int Category_Id { get; set; }
        public virtual Category Category { get; set; }
    }
}
